# ----------------------------
# Makefile Options
# ----------------------------

NAME = RAWVIEW
ICON = icon.png
DESCRIPTION = "RGB565 Raw image viewer"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
