# ----------------------------
# Makefile Options
# ----------------------------

NAME = PNGVIEW
ICON = icon.png
DESCRIPTION = "View PNG from USB disk"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
