# ----------------------------
# Makefile Options
# ----------------------------

NAME = PNGVIEW
ICON = icon.png
DESCRIPTION = "View PNG from USB disk"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

EXTRA_C_SOURCES = upng/upng.c
EXTRA_HEADERS = upng/upng.h

# ----------------------------

include $(shell cedev-config --makefile)
